### ISSUE TITLE
css冲突

### ISSUE THREAD

**Issue by 233cy** [fjc0k/vue-iconfont#1]
应该增加默认CSS设置接口，而不是开始就强制了用户的css设置，
这样无法让我自定义字体大小，然而我不想在标签中写style，而只是设置一个默认值，或让他根据父div大小走即可

**Comment by fjc0k** [comment]
ok，下班看看。在这之前，你能提供一个演示吗？https://jsfiddle.net/

**Comment by fjc0k** [comment]
@Wfuren 你可以直接使用 class：

```html
<icon name="start" class="myIcon" />
```

```css
.myIcon {
  font-size: 1em; // 事实上，vue-iconfont 的图标默认大小就是 1em，即和父元素大小一致
  color: red;
}
```
